### PR TITLE
fix: use Scrollable.ensureVisible for accurate verse scroll positioni…

### LINKED ISSUE #53: Bug: Navigation to bookmarks is inaccurate at high font scales
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Steps to reproduce

1. use big font size ex:45
2. click on a saved bookmark

### Expected results

go to the exact verse

### Actual results

it doesnt go to the exact verse

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/5cdb4332-7d3b-45d2-b3a5-b776bd830772

</details>

### App Version

1.3-1.7

### Environment

- OS version: 15

### Platform

Android

### PR DESCRIPTION
**Pull request by Hy4ri**
closes #53 

Replace the ratio-based scroll alignment with Scrollable.ensureVisible targeting an inline WidgetSpan sentinel at the exact highlighted verse position. This ensures correct scroll behavior at all font sizes.

- Add GlobalKey plumbed through QuranPageWidget to _SurahTextBlock
- Insert zero-size keyed WidgetSpan before highlighted verse text
- Use double post-frame callback for reliable ensureVisible after jump
- Remove dead quran_helpers.dart (getVerseAlignmentOnPage unused)

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read and followed the [Flutter Style Guide].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making.
- [ ] I followed the [Data Driven Fixes] where supported.
- [ ] I bumped the package version following the [Semantic Versioning](https://semver.org/) guidelines (For now the major is the second number and the minor the third, because the package is not feature complete). For example, if the package is at version `0.18.0` and you introduced a breaking change or a new feature, bump it to `0.19.0`, if you just added a fix or a chore bump it to `0.18.1`.
- [ ] I updated the `CHANGELOG.md` file with a summary of changes made following the format already used.

### CODE REVIEW

**Comment by DMouayad** [comment]
جزاك الله خيراً
I'll review as soon as I can

File: lib/app/pages/home_page.dart [hunk 1]
```diff
@@ -200,21 +204,31 @@ class HomePageState extends State<HomePage> with WidgetsBindingObserver {
...
+          if (ctx != null) {
+            Scrollable.ensureVisible(
+              ctx,
+              alignment: 0.25,
+              duration: const Duration(milliseconds: 250),
+              curve: Curves.easeOutCubic,
+            );
+          }
+        });
+      });
```
Comment (DMouayad) [inline lib/app/pages/home_page.dart]: is it really needed to have two `addPostFrameCallback` ? I tested it with only one and it works, no issues.

File: lib/app/pages/home_page.dart [hunk 2]
```diff
@@ -200,21 +204,31 @@ class HomePageState extends State<HomePage> with WidgetsBindingObserver {
...
+    if (highlightSurah != null && highlightVerse != null) {
+      // Double post-frame callback: first frame builds the page,
+      // second frame ensures layout is settled before ensureVisible.
+      WidgetsBinding.instance.addPostFrameCallback((_) {
+        WidgetsBinding.instance.addPostFrameCallback((_) {
+          final ctx = _highlightedBlockKey.currentContext;
+          if (ctx != null) {
+            Scrollable.ensureVisible(
+              ctx,
+              alignment: 0.25,
```
Comment (DMouayad) [inline lib/app/pages/home_page.dart]:
```suggestion
       alignment: highlightVerse == 1 ? 1 : 0.25,
```
this ensures the surah name and basmala is visible for the first verse.

File: lib/app/pages/home_page.dart (hunk 1 above)
Comment (Hy4ri) [reply lib/app/pages/home_page.dart]: > is it really needed to have two `addPostFrameCallback` ? I tested it with only one and it works, no issues.

Its acts as an insurance policy. It guarantees that slower, older Android phones have enough time (2 frames) to fully render the complex text before calculating the exact pixel offset.

File: lib/app/pages/home_page.dart [hunk 3]
```diff
@@ -200,21 +204,31 @@ class HomePageState extends State<HomePage> with WidgetsBindingObserver {
...
+              duration: const Duration(milliseconds: 250),
+              curve: Curves.easeOutCubic,
+            );
+          }
+        });
+      });
     }
   }
```
Comment (DMouayad) [inline lib/app/pages/home_page.dart]:
```suggestion
    // 3. After the page renders, scroll to the highlighted verse block.
    if (highlightSurah != null && highlightVerse != null) {
      unawaited(_scrollToHighlightedVerse(highlightVerse));
    }
  }

  Future<void> _scrollToHighlightedVerse(int highlightVerse) async {
    for (int i = 0; i < 2; i++) {
      await WidgetsBinding.instance.endOfFrame;
      if (!mounted) return;

      final ctx = _highlightedBlockKey.currentContext;
      if (ctx == null || !ctx.mounted) continue;
      
      final isFirstSurahVerse = highlightVerse == 1;
      final double alignment = isFirstSurahVerse
          ? widget.settingsController.isHorizontalScrolling
                ? 1
                : 0.6
          : 0.25;
      await Scrollable.ensureVisible(
        ctx,
        alignment: alignment,
        duration: const Duration(milliseconds: 250),
        curve: Curves.easeOutCubic,
      );
      return;
    }
  }

```

let's use this method, we verify if the highlighted block has been rendered after 2 frames.
also if fixed the alignment for page/vertical scrolling modes.

Comment (DMouayad) [reply lib/app/pages/home_page.dart]: I did test this on a low-end mobile and in debug mode and no issues, alhamdulillah.
