### PR TITLE
fix: dynamic color showing same surface for all elements

### LINKED ISSUE #54: Android material theming not using correct colors
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Steps to reproduce

1. Enable dynamic theming in the app

### Expected results

Colors of background and menus are different
Image

### Actual results

Colors of background and menus are the same
Image

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### App Version

1.7.0

### Environment

- Flutter version:
- Device model:
- OS version:

### Platform

Android

### PR DESCRIPTION
**Pull request by Tid0lla**
Fixed an issue where dynamic color theming results in the app using `colorScheme.surface` for everything, making all surfaces appear as the same color.

Resolve #54 

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read and followed the [Flutter Style Guide].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making.
- [x] I followed the [Data Driven Fixes] where supported.
- [x] I bumped the package version following the [Semantic Versioning](https://semver.org/) guidelines (For now the major is the second number and the minor the third, because the package is not feature complete). For example, if the package is at version `0.18.0` and you introduced a breaking change or a new feature, bump it to `0.19.0`, if you just added a fix or a chore bump it to `0.18.1`.
- [x] I updated the `CHANGELOG.md` file with a summary of changes made following the format already used.

### CODE REVIEW

File: lib/app/theme.dart [hunk 1]
```diff
@@ -69,8 +69,8 @@ ThemeData _buildMyQuranDark() {
 }
 
 ThemeData _buildDynamicLight(ColorScheme? deviceScheme) {
-  final colorScheme =
-      deviceScheme ?? ColorScheme.fromSeed(seedColor: Colors.blue);
+  final seedColor = deviceScheme?.primary ?? Colors.blue;
+  final colorScheme = ColorScheme.fromSeed(seedColor: seedColor);
```
Comment (DMouayad) [inline lib/app/theme.dart]:
```suggestion
  final seedColor = deviceScheme?.primary ?? Colors.blue;
  final colorScheme = ColorScheme.fromSeed(
    seedColor: seedColor,
    secondary: deviceScheme?.secondary,
    tertiary: deviceScheme?.tertiary,
  );
```

**Comment by DMouayad** [comment]
@Tid0lla should I make the requried changes? I want to include this in next release. pleas lmk
